more

diff --git a/hugodir b/hugodir
--- a/hugodir
+++ b/hugodir
@@ -1,30 +1,42 @@
 #!/bin/sh
 
+EP_MIMETYPE=mimetype
+
 usage() {
+  echo "Error: '$1'"
+  echo
   echo Usage:
-  echo "  $0 [hugoFlags] -- draftRegex epubfile [dest-dir]"
+  echo "  $0 [hugoFlags] -- draftRegex epubfile [destdir]"
   exit 1
 
 }
 
 have_cmd(){
   command -v $1 >/dev/null 2>&1 || {
-    echo >&2 "I require [$1] but it's not installed."
-    echo >&2 "Aborting."
+    echo >&2
+    echo >&2 " - I require [$1] but it's not installed."
+    echo >&2 "   Aborting."
     exit 1; }
 }
 
 file_chk(){
   stat $1 >/dev/null 2>&1 || {
     echo >&2 "File not found; '$1'"
-    exit 1; }
+    test -z "$2" && exit 1; }
 }
+
+
+printf "* Checking availiable COMMANDs in system..."
 
 have_cmd grep
 have_cmd stat
+have_cmd readlink
 have_cmd hugo
 have_cmd xsltproc
 
+echo "ok"
+
+alias realpath="readlink -f"
 
 
 # TODO grab ALL flags and shift;shift;shift until no more flags
@@ -32,25 +44,35 @@ have_cmd xsltproc
 ISDRAFT_REGEX=$1
 EPUB=$2
 
-echo ------ DEBUG -------------
-echo ISDRAFT_REGEX = $ISDRAFT_REGEX
-echo EPUB = $EPUB
-echo ==========================
-
-test -z $ISDRAFT_REGEX && usage 
-test -z $EPUB && usage 
+test -z $ISDRAFT_REGEX && usage "draftRegex empty" 
+test -z $EPUB && usage "epubfile empty"
 
 
 if test -d "$EPUB"; then
   echo "* epubfile is assumed to be extracted-dir."
-  file_chk "$EPUB/META-INF/container.xml"
+  file_chk "$EPUB/$EP_MIMETYPE"
 else
   echo "* epubfile must be unzipped."
+  ZIPPED=1
   file_chk "$EPUB"
   have_cmd unzip
 fi
 
-HUGODIR=${3:-$(dirname $EPUB)}
+ep_dir=$(realpath $(dirname $EPUB))
+
+HUGODIR=$(realpath ${3:-$ep_dir})
+file_chk $HUGODIR warn-only
+
+echo ep_dir = $ep_dir
 echo HUGODIR = $HUGODIR
-file_chk $HUGODIR
+
+# Unzip or CP if needed
+if test "$ZIPPED" = "1"
+then
+  unzip "$EPUB" -d "$HUGODIR"
+elif test ! "$HUGODIR" = "$ep_dir"
+then
+  mkdir -p $HUGODIR
+  cp -r "$EPUB/*" "$HUGODIR"
+fi
 
